version: '2.2'

services:
    dm:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: intent
        network_mode: host
        volumes:
            - ./dm_intent:/workspace/src
